dist: bionic
before_install:
  - sudo apt-get update
  - sudo apt-get install -y libblosc1
  - sudo apt-get install -y python3-setuptools
  - sudo apt install -y python3-pip
  - sudo pip3 install zarr
language: java
jdk: openjdk10
branches:
  only:
  - master
  - "/.*-[0-9]+\\..*/"
  
